### ISSUE TITLE
hdmi capture device

### ISSUE THREAD

**Issue by niko2** [Fmstrat/diy-ipmi#1]
Why don't you use directly an hdmi capture device ?
https://www.amazon.com/Video-Capture-Device-Windows-System-Including/dp/B075N7FDMN/ref=sr_1_8?s=electronics&ie=UTF8&qid=1511565304&sr=1-8&keywords=usb+video+capture+vga

**Comment by Fmstrat** [comment]
Are you able to locate one that works in Raspbian?

**Comment by niko2** [comment]
Yes. I missed the driver issue...
I found one but it is too expensive. 
https://store.techexport.com/collections/e-mediavision/products/pz-hdmi

**Comment by Fmstrat** [comment]
Yup, I've seen that one as well, but for that price, you could buy a pro IPMI/KVM systrem :) Closing this out, but if one becomes available for cheap, let me know!
