### ISSUE TITLE
No reboot needed - can i skip the relay board?

### ISSUE THREAD

**Issue by moose999** [Fmstrat/diy-ipmi#12]
Hi,

Similar to others on here, I am looking at this for remote support for users who are present, so am not worried about remote reboot. Does this mean i can leave the relay board out completely, and therefore the GPIO pins and cables?

Thanks for a great project!
Justin

**Comment by moose999** [comment]
BTW - I should have mentioned - I am going to use a Pi Zero with pre-soldered pins 
https://thepihut.com/collections/raspberry-pi-zero/products/raspberry-pi-zero-wh-with-pre-soldered-header

**Comment by Fmstrat** [comment]
Yes, that is correct. You do not need the relay board in this scenario.
