### ISSUE TITLE
What are the hard dependencies on Raspbian for the Pi3?

### ISSUE THREAD

**Issue by seffyroff** [Fmstrat/diy-ipmi#24]
In your install guide you state the versions of OS to install on each device, and that a newer version of Raspbian Stretch will probably work on the Pi3 - what are the dependencies here for the Pi3, (and also the Pi0, out of curiosity?),

**Comment by spyd3rweb** [comment]
With this latest pull request (https://github.com/Fmstrat/diy-ipmi/pull/26) it will work with the the latest Raspbian Stretch Lite (2018-10-09) on both the Raspberry Pi3 and Pi0 W. There were some slight modifications needed within "checkPi0Login.sh".

**Comment by seffyroff** [comment]
Your PR looks great.  I have some other issues with this repo at it's current state, which I've overcome in my own fork, but I hope yours gets merged soon!
