### ISSUE TITLE
Can't access Pi0 via Serial

### ISSUE THREAD

**Issue by SterlingButters** [Fmstrat/diy-ipmi#9]
You can get the details of my issue here: 

https://raspberrypi.stackexchange.com/questions/82911/cant-login-to-pi0-console-from-pi3-b-via-uart-serial-usb-tty-adapter?noredirect=1#comment131471_82911

I do get a blank screen via `screen /dev/ttyUSB0 115200` but no matter how many times I press enter, a blank screen is all I see. Not sure if it is a driver related issue or what but I can't seem to figure it out.

Do I need to be passing a parameter?:

```
Name:   dwc2
Info:   Selects the dwc2 USB controller driver
Load:   dtoverlay=dwc2,<param>=<val>
Params: dr_mode                 Dual role mode: "host", "peripheral" or "otg"

        g-rx-fifo-size          Size of rx fifo size in gadget mode

        g-np-tx-fifo-size       Size of non-periodic tx fifo size in gadget
                                mode

        g-tx-fifo-size          Size of periodic tx fifo per endpoint
                                (except ep0) in gadget mode
```

**Comment by SterlingButters** [comment]
Turns out it was some electrical issue with my Pi0

**Comment by Rivest8** [comment]
What was the solution? I am having the same problem with the blank screen.
I found if you press CTRL + C then the "pi@raspberrypi:~$" text comes up and I am able to enter commands. So it is communicating with the Pi0 but, once I Type the test command "echo 'a' | /home/pi/sendkeys /dev/hidg0 keyboard" then it goes back to that blank screen. I cant get the computer to recognize any keyboard commands from the Pi0.

**Comment by SterlingButters** [comment]
Let me know if this helps:
https://raspberrypi.stackexchange.com/questions/83209/blank-terminal-in-pi0-uart-connection?noredirect=1#comment131996_83209

**Comment by Rivest8** [comment]
Thank you, Turns out the pi0 was actually working fine for me. The console is just blank until you hit any key which is ok... The issue with the keys not being recognized is actually an issue with the system I have it plugged into and not the PI KVM setup.
